name: Update Index

on:
   push:
      branches: [ main ]


jobs:
   build:
      runs-on: ubuntu-20.04
      steps:
         # Checks out this repo so workflow can access it
         # https://github.com/actions/checkout
         - name: Git Checkout
           uses: actions/checkout@v4
         
         # Installs helm
         # https://github.com/Azure/setup-helm
         - name: Helm Installation
           uses: azure/setup-helm@v4.2.0
           with:
               version: 'v3.16.1'
         
         # Updates Index file
         -  name: Update Index
            env:
               GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            run: |
               helm repo index .
               git config --local user.email "action@github.com"
               git config --local user.name "GitHub Action"
               git add index.yaml
               git commit -m "Updated chart index"
               git push